### ISSUE TITLE
Test flow - PZ

### ISSUE THREAD

**Issue by zakp** [macicekz/statusDashboardTool#2]
This is just a test... I would like to see whole flow until it is resolved.

BTW: this is what I can see in https://github.com/macicekz/statusDashboardTool/releases/tag/2.9

./wizzard_new.sh: line 397: ./allOK_ALL.sh: No such file or directory

Thank you
Pavel

**Comment by macicekz** [comment]
Its a known issue. Release description updated....
It does not have impact till DC NA2 will be in production.
